#define failwith(s)      caml_failwith(s)
#define alloc_small(a,b) caml_alloc_small(a,b)
#define string_length(a) caml_string_length(a)
#define alloc_tuple(a)   caml_alloc_tuple(a)
#define stat_alloc(a)    caml_stat_alloc(a)
#define stat_free(a)     caml_stat_free(a)
#define alloc_string(a)  caml_alloc_string(a)
#define copy_double(a)   caml_copy_double(a)
#define alloc(a,b)       caml_alloc(a,b)
#define copy_string(a)   caml_copy_string(a)

